"""
Simple Encryption and Decryption python program.
Author = Satshree Shrestha
Date started = 5/29/2019
First stable version created = 6/1/2019
"""

from datetime import datetime

def writeEncrypt(msg):

    format_="%Y-%m-%d %I:%M %p"
    now = "Encryption done on " + datetime.strftime(datetime.now(),format_)
    file = open("Encrypted Message.txt", "w")
    file.write("*******************************************************************************\n")
    file.write("The following is the encrypted message that has been generated by this program.\n")
    file.write(now)
    file.write("\n*******************************************************************************\n\n")
    file.write(msg)
    file.write("\n\n*******************************************************************************\n")
    file.write("You can copy and paste this cipher text in this program again to decrypt.\n")
    file.write("Make sure to keep the key safe because without it, the message cannot be decrypted!\n")
    file.write("*******************************************************************************\n")
    file.write("Thank you for using this program\n\nDeveloper: Satshree Shrestha, Nepal\n")
    file.write("*******************************************************************************")
    file.close

def writeDecrypt(msg):

    format_="%Y-%m-%d %I:%M %p"
    now = "Decryption done on " + datetime.strftime(datetime.now(),format_)
    file = open("Decrypted Message.txt", "w")
    file.write("*******************************************************************************\n")
    file.write("The following is the decrypted message that has been generated by this program.\n")
    file.write(now)
    file.write("\n*******************************************************************************\n\n")
    file.write(msg)
    file.write("\n*******************************************************************************\n")
    file.write("Thank you for using this program\n\nDeveloper: Satshree Shrestha, Nepal\n")
    file.write("*******************************************************************************\n")
    file.close

def writeKey(key):

    file = open("KEY.txt", "w")
    file.write("*******************************************************************************\n")
    file.write("The following is the key used for encryption.\n")
    file.write("Use this key for the decryption.\n")
    file.write("*******************************************************************************\n\n")
    file.write(key)
    file.write("\n\n*******************************************************************************\n")
    file.write("Make sure to keep this key safe because without it, the message cannot be decrypted!\n")
    file.write("*******************************************************************************\n")
    file.write("Thank you for using this program\n\nDeveloper: Satshree Shrestha, Nepal\n")
    file.write("*******************************************************************************\n")
    file.close
    
